{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "code-marketplace.fullname" . }}-vs
  labels:
    {{- include "code-marketplace.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ingress.host }}
  gateways:
    - {{ include "code-marketplace.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "code-marketplace.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end }}
